admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

app_speciality:
    resource: "@AdminBundle/Controller/SpecialityController.php"
    type:     annotation

app_pediatrician:
    resource: "@AdminBundle/Controller/PediatricianController.php"
    type:     annotation
