admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

app_speciality:
    resource: "@AdminBundle/Controller/SpecialityController.php"
    type:     annotation

admin_event:
    resource: "@AdminBundle/Controller/EventController.php"
    type:     annotation